# Ejemplo 03

En este ejemplo vamos a mutar un individuo. En la mutación original el individuo mutado puede tener un problema severo y volverse ineficaz, pero en esta versión modificada de mutación, se copia un individuo y se realiza la mutación sobre él. De esta manera solamente las mutaciones eficaces se mantienen y las ineficaces se descartarán.

Primero, vamos a tomar las funciones del ejemplo 01 y algunas del ejemplo 02 

In [1]:
import numpy as np
import random as rnd

def inicializarIndividuo(individuo):
    total = 1.0
    cantidadGenes = len(individuo)
    for counter in range(0,cantidadGenes):
        if(counter == cantidadGenes -1):
            individuo[counter] = total
        else:  
            randomValue = rnd.uniform(0,total)
            individuo[counter] = randomValue
            total -=randomValue
    return individuo

def generarPoblacion(cantidadDeIndividuos, cantidadDeGenes):
    poblacion = np.zeros((cantidadDeIndividuos, cantidadDeGenes))
    for counter in range(0,cantidadDeIndividuos):
        poblacion[counter] = inicializarIndividuo(poblacion[counter])
    return poblacion

def ajustarIndividuo(individuo):
    total = np.sum(individuo)
    individuo = individuo / total
    return individuo  

## Mutación:
Un individuo sometido a mutación debe de sufrir un cambio sutil en su genotipo, para ello, al individuo elegido vamos a hacer que en algun punto de sus genes el valor se incremente de 0.1 a 0.3 (10 al 30% de incremento por mutación). Despues, vamos a copiarl al individuo, vamos a ajustar su gen elegido aleatoriamente, y luego lo ajustamos para que valga 1.0

In [2]:
def mutacion(individuo):
    mutationPoint = rnd.randint(1,len(individuo)-2)
    mutationValue = rnd.uniform(0.1, 0.3)
    individuoMutante = np.array(individuo, copy=True)
    individuoMutante[mutationPoint] +=mutationValue
    individuoMutante = ajustarIndividuo(individuoMutante)
    return np.array([individuoMutante])

## Mutación de la población:
Por lo general una mutación de la población debe ser de una probabilidad muy baja, para que muy pocos individuos se vean afectados. En este algoritmo de mutación puedes elegir la probabilidad que desees, ya que al final serán eliminadas las mutaciones desagradables.

In [8]:
def mutarPoblacion(poblacion, probabilidadDeMutacion):
    nuevaPoblacion = None
    for counter in range(len(poblacion)):
        probabilidad = rnd.random()
        if(probabilidad < probabilidadDeMutacion):
            nuevoMutante = mutacion(poblacion[counter])
            if nuevaPoblacion is None:
                nuevaPoblacion = nuevoMutante
            else:
                nuevaPoblacion = np.concatenate((nuevaPoblacion,nuevoMutante))
    if not nuevaPoblacion is None:        
        poblacion = np.concatenate((poblacion, nuevaPoblacion))
    return poblacion

## Prueba de mutacion

In [9]:
poblacion = generarPoblacion(6,4)
print("poblacion original")
print(poblacion)

#50% de mutantes es muchisimo, pero es para probar.
poblacion = mutarPoblacion(poblacion,0.5)
print("población + mutantes")
print(poblacion)

poblacion original
[[0.53460463 0.29986701 0.11633647 0.04919189]
 [0.81758399 0.13116321 0.01175237 0.03950043]
 [0.25456443 0.6220495  0.06052234 0.06286374]
 [0.45935025 0.02989449 0.30258226 0.208173  ]
 [0.09456538 0.5224539  0.03962547 0.34335525]
 [0.49214659 0.06065541 0.12604833 0.32114967]]
población + mutantes
[[0.53460463 0.29986701 0.11633647 0.04919189]
 [0.81758399 0.13116321 0.01175237 0.03950043]
 [0.25456443 0.6220495  0.06052234 0.06286374]
 [0.45935025 0.02989449 0.30258226 0.208173  ]
 [0.09456538 0.5224539  0.03962547 0.34335525]
 [0.49214659 0.06065541 0.12604833 0.32114967]
 [0.48033375 0.37094165 0.10452647 0.04419813]
 [0.41399326 0.12568428 0.2727048  0.18761766]
 [0.41739004 0.05144192 0.25880067 0.27236737]]
