# Reto 02
Une el ejemplo 01, 02 y 03 en un solo cuaderno: 
- Inicializa una población 
- Realiza la cruza de sus individuos.
- Realiza la mutación de la población.

Si lograste hacerlo, deberás ser capaz de generar una población, cruzarla, y mutarla.

In [1]:
import numpy as np
import random as rnd

### Funciones del ejemplo 01.

In [2]:
def inicializarIndividuo(individuo):
    total = 1.0
    cantidadGenes = len(individuo)
    #Por cada uno de los genes...
    for counter in range(0,cantidadGenes):
        #Si llegaste al último gen, pon lo que sobre a este gen.
        if(counter == cantidadGenes -1):
            individuo[counter] = total
        #Sino, 
        else:  
            #obten un valor aleatorio entre 0 y lo que quede del 100%
            randomValue = rnd.uniform(0,total)
            #Dale ese valor aleatorio a ese gen.
            individuo[counter] = randomValue
            #Y resta lo que obtuviste del 100% original.
            total -=randomValue
    return individuo

def generarPoblacion(cantidadDeIndividuos, cantidadDeGenes):
    #reservamos la memoria que usarán los individuos: Todos los individuos nacen con genes en 0.
    poblacion = np.zeros((cantidadDeIndividuos, cantidadDeGenes))
    #Y a cada individuo se le inicializan los genes con la función "inicializar individuo"
    for counter in range(0,cantidadDeIndividuos):
        poblacion[counter] = inicializarIndividuo(poblacion[counter])
    return poblacion

### Funciones del ejemplo 02.

In [3]:
def ajustarIndividuo(individuo):
    total = np.sum(individuo)
    individuo = individuo / total
    return individuo    

def cruzarIndividuos(individuo1, individuo2):
    crossPoint = rnd.randint(1,len(individuo1)-2)
    hijo1 = np.append(individuo1[0:crossPoint], individuo2[crossPoint:len(individuo1)])
    hijo2 = np.append(individuo2[0:crossPoint], individuo1[crossPoint:len(individuo1)])
    hijo1 = ajustarIndividuo(hijo1)
    hijo2 = ajustarIndividuo(hijo2)
    return np.array([hijo1,hijo2])

def cruzarPoblacion(poblacion, probabilidadDeCruza):    
    nuevaPoblacion = None
    for counter in range(len(poblacion)):
        probabilidad = rnd.random()
        #Si la probabilidad es menor que la probabilidad de cruza, entonces se procede a la cruza.
        if(probabilidad < probabilidadDeCruza):
            #Elige pareja:
            pareja = rnd.randint(0,len(poblacion)-2)
            #Si al elegir una pareja, elegiste sin querer al mismo individuo, intenta de nuevo.
            while pareja == counter:
                pareja = rnd.randint(0,len(poblacion)-2)
            
            #Haz la cruza. 
            nuevosIndividuos = cruzarIndividuos(poblacion[counter],poblacion[pareja])
            
            #Añade los nuevos individuos a una lista de nuevos individuos.
            if nuevaPoblacion is None:
                nuevaPoblacion = nuevosIndividuos
            else:
                nuevaPoblacion = np.concatenate((nuevaPoblacion,nuevosIndividuos))
                
    #Al final del ciclo, si hay nuevos individuos, añadelos a la población.
    if not nuevaPoblacion is None:
        poblacion = np.concatenate((poblacion, nuevaPoblacion))
    return poblacion

### Funciones del ejemplo 03.

In [4]:
def mutacion(individuo):
    mutationPoint = rnd.randint(1,len(individuo)-2)
    mutationValue = rnd.uniform(0.1, 0.3)
    individuoMutante = np.array(individuo, copy=True)
    individuoMutante[mutationPoint] +=mutationValue
    individuoMutante = ajustarIndividuo(individuoMutante)
    return np.array([individuoMutante])

def mutarPoblacion(poblacion, probabilidadDeMutacion):
    nuevaPoblacion = None
    for counter in range(len(poblacion)):
        probabilidad = rnd.random()
        if(probabilidad < probabilidadDeMutacion):
            nuevoMutante = mutacion(poblacion[counter])
            if nuevaPoblacion is None:
                nuevaPoblacion = nuevoMutante
            else:
                nuevaPoblacion = np.concatenate((nuevaPoblacion,nuevoMutante))
    if not nuevaPoblacion is None:        
        poblacion = np.concatenate((poblacion, nuevaPoblacion))
    return poblacion

### Unión de los ejemplos 01, 02 y 03 en un solo código.

In [5]:
poblacion = generarPoblacion(10,3)
print("Poblacion original:")
print(poblacion)

poblacion = cruzarPoblacion(poblacion, 0.3)
print("Población con hijos añadidos:")
print(poblacion)

poblacion = mutarPoblacion(poblacion,0.3)
print("población + hijos + mutantes")
print(poblacion)

Poblacion original:
[[0.20029823 0.04746856 0.75223321]
 [0.02065728 0.33157617 0.64776655]
 [0.50551916 0.37707506 0.11740578]
 [0.79400336 0.17844675 0.0275499 ]
 [0.11531978 0.06458992 0.82009029]
 [0.6339995  0.0990013  0.2669992 ]
 [0.57229087 0.13474357 0.29296556]
 [0.46658007 0.36938507 0.16403486]
 [0.84257586 0.10120924 0.05621489]
 [0.58313113 0.39863979 0.01822908]]
Población con hijos añadidos:
[[0.20029823 0.04746856 0.75223321]
 [0.02065728 0.33157617 0.64776655]
 [0.50551916 0.37707506 0.11740578]
 [0.79400336 0.17844675 0.0275499 ]
 [0.11531978 0.06458992 0.82009029]
 [0.6339995  0.0990013  0.2669992 ]
 [0.57229087 0.13474357 0.29296556]
 [0.46658007 0.36938507 0.16403486]
 [0.84257586 0.10120924 0.05621489]
 [0.58313113 0.39863979 0.01822908]
 [0.31894249 0.21455731 0.4665002 ]
 [0.41712386 0.03459826 0.54827787]
 [0.21236398 0.24813333 0.53950269]
 [0.39279494 0.04433164 0.56287342]
 [0.54307774 0.31641162 0.14051065]
 [0.56040231 0.11890897 0.32068873]
 [0.51757735 