# Ejemplo 04

En este ejemplo vamos a evaluar una población, y eliminaremos aquellos individuos que no sean aptos, dejando solamente los N mas aptos. Para ello, requeriremos las funciones del ejemplo 01 y 02.

In [1]:
import numpy as np
import random as rnd

def inicializarIndividuo(individuo):
    total = 1.0
    cantidadGenes = len(individuo)
    for counter in range(0,cantidadGenes):
        if(counter == cantidadGenes -1):
            individuo[counter] = total
        else:  
            randomValue = rnd.uniform(0,total)
            individuo[counter] = randomValue
            total -=randomValue
    return individuo

def generarPoblacion(cantidadDeIndividuos, cantidadDeGenes):
    poblacion = np.zeros((cantidadDeIndividuos, cantidadDeGenes))
    for counter in range(0,cantidadDeIndividuos):
        poblacion[counter] = inicializarIndividuo(poblacion[counter])
    return poblacion

def ajustarIndividuo(individuo):
    total = np.sum(individuo)
    individuo = individuo / total
    return individuo  

## Evaluación:
La función de evaluación es la clave de todo el algoritmo genético. Si un algoritmo genético no tiene una función de evaluación correcta, el resultado será mediocre (cuando mucho). La función objetivo debe de evaluar a cada individuo y obtenerle un "puntaje" de que tan buena es la solución. A mas puntaje, mejor solución.

Esta función no es trivial de obtener y depende de cada problema que vayas a tratar. No existe una fórmula mágica para obtenerla y dependerá de tu talento con los algoritmos.

In [8]:
def evaluacion(poblacion, ganancias, probabilidadDeExito):
    puntaje = np.zeros(poblacion.shape[0])

    puntajeDeGanancia = np.dot(poblacion, ganancias)
    puntajeDeExito = np.dot(poblacion, probabilidadDeExito)
    puntaje = puntajeDeGanancia+puntajeDeExito
    
    ordenDeMayorAMenor = np.argsort(-puntaje)
    poblacionOrdenada = poblacion[ordenDeMayorAMenor]
    mejorPuntaje = (np.sort(-puntaje)[0])*-1
    return poblacionOrdenada, mejorPuntaje

## Eliminar individuos.
Una vez ordenados de mayor a menor, habrá que eliminar a los individuos menos aptos: Puede ser por porcentaje o por cantidad. Te recomiendo encarecidamente eliminar individos por cantidad, mas no por porcentaje: debes mantener un gran control de la población si eliminas por porcentaje, ya que puedes llegar a la sobrepoblación y cada generación será cada vez mas grande, lo que acabará con tu memoria RAM

In [9]:
def eliminarIndividuosPorPorcentaje(poblacion, porcentajeAMantener):
    cantidad = poblacion.shape[0]
    cantidadAMantener = int(porcentajeAMantener * cantidad)
    return poblacion[:cantidadAMantener]
    
def eliminarIndividuosPorCantidad(poblacion, cantidadAMantener):    
    return poblacion[:cantidadAMantener]

# Prueba de evaluación y eliminación de individuos

In [17]:
poblacion = generarPoblacion(6,4)
print("Poblacion original")
print(poblacion)

ganancias = [0.1,0.2,0.9,0.4]
probabilidadDeExito = [0.2,0.5,0.5,0.2]

poblacion,mejorPuntaje= evaluacion(poblacion,ganancias, probabilidadDeExito)
print("\nPoblacion evaluada y ordenada de mejor a peor:\n")
print(poblacion)

print("\nMejor puntaje:"+str(mejorPuntaje)+"\n")

poblacion = eliminarIndividuosPorCantidad(poblacion, 3)
print("Poblacion superviviente:")
print(poblacion)

Poblacion original
[[7.28504738e-01 3.28138170e-02 1.74891124e-01 6.37903207e-02]
 [1.38484907e-02 6.16462602e-01 2.27474377e-01 1.42214530e-01]
 [2.55010658e-01 6.02400390e-01 3.05185870e-03 1.39537093e-01]
 [2.54636579e-01 4.99852572e-01 2.45476080e-01 3.47694398e-05]
 [7.27962522e-01 1.03001114e-01 1.39179729e-01 2.98566354e-02]
 [5.86677361e-01 1.99160429e-01 1.36823545e-01 7.73386655e-02]]

Poblacion evaluada y ordenada de mejor a peor:

[[1.38484907e-02 6.16462602e-01 2.27474377e-01 1.42214530e-01]
 [2.54636579e-01 4.99852572e-01 2.45476080e-01 3.47694398e-05]
 [2.55010658e-01 6.02400390e-01 3.05185870e-03 1.39537093e-01]
 [5.86677361e-01 1.99160429e-01 1.36823545e-01 7.73386655e-02]
 [7.28504738e-01 3.28138170e-02 1.74891124e-01 6.37903207e-02]
 [7.27962522e-01 1.03001114e-01 1.39179729e-01 2.98566354e-02]]

Mejor puntaje:0.839471214485776

Poblacion superviviente:
[[1.38484907e-02 6.16462602e-01 2.27474377e-01 1.42214530e-01]
 [2.54636579e-01 4.99852572e-01 2.45476080e-01 3.476